apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: oauth-openshift-really-long-lalalalalalalalala
  namespace: openshift-authentication
spec:
  port:
    targetPort: 6443
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: passthrough
  to:
    kind: Service
    name: oauth-openshift
    weight: 100
  wildcardPolicy: None
