apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    control-plane: updateservice-operator
  name: updateservice-operator-metrics
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: updateservice-operator
status:
  loadBalancer: {}
