apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: updateservice-operator-metrics-tls
  labels:
    name: updateservice-operator
  name: updateservice-operator-metrics
  namespace: openshift-update-service
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    name: updateservice-operator
