apiVersion: apps/v1
kind: Deployment
metadata:
  name: cincinnati-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cincinnati-operator
  template:
    metadata:
      labels:
        name: cincinnati-operator
    spec:
      serviceAccountName: cincinnati-operator
      containers:
        - name: cincinnati-operator
          # TODO Replace this with the built image name
          image: quay.io/rwsu/cincinnati-operator:latest
          command:
          - cincinnati-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cincinnati-operator"
              # pick a new value from https://quay.io/repository/app-sre/cincinnati?tag=latest&tab=tags
            - name: OPERAND_IMAGE
              value: "quay.io/app-sre/cincinnati:2873c6b"
