kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cincinnati-operator
subjects:
- kind: ServiceAccount
  name: cincinnati-operator
  namespace: openshift-cincinnati
roleRef:
  kind: ClusterRole
  name: cincinnati-operator
  apiGroup: rbac.authorization.k8s.io
