apiVersion: cincinnati.openshift.io/v1beta1
kind: Cincinnati
metadata:
  name: example
spec:
  replicas: 1
  registry: "quay.io"
  repository: "openshift-release-dev/ocp-release"
  graphDataImage: graph-data:latest
